openapi: 3.0.0
info:
  title: Sample Inventory API
  version: 1.0.0
  description: |
    A simple service for managing inventory items. The API supports creating,
    listing, updating and deleting items and is useful for testing typical
    business workflows.
paths:
  /ping:
    get:
      summary: Health check
      operationId: controllers.ping
      responses:
        '200':
          description: Returns pong message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: pong
  /items:
    get:
      summary: List all items
      operationId: controllers.list_items
      responses:
        '200':
          description: List of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      summary: Create a new item
      operationId: controllers.create_item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemInput'
      responses:
        '201':
          description: Created item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
  /items/{id}:
    get:
      summary: Get item by ID
      operationId: controllers.get_item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Item detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Not found
    put:
      summary: Update item
      operationId: controllers.update_item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemInput'
      responses:
        '200':
          description: Updated item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Not found
    delete:
      summary: Delete item
      operationId: controllers.delete_item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Deleted item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Not found
components:
  schemas:
    Item:
      type: object
      description: An inventory record identified by an integer ID and a name.
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: example item
    ItemInput:
      type: object
      description: Payload used when creating or updating an inventory item.
      required:
        - name
      properties:
        name:
          type: string
          example: example item
